# Generated by Django 5.0.6 on 2024-07-11 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('chofer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('litros', models.IntegerField()),
                ('tipo_gasolina', models.IntegerField(choices=[(0, 'Gasolina'), (1, 'Diesel'), (2, 'Gas')])),
                ('precio_litro', models.FloatField()),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruta_camion', to='api.camion')),
            ],
        ),
        migrations.CreateModel(
            name='RutaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surtidor', models.IntegerField()),
                ('orden', models.IntegerField()),
                ('litros', models.IntegerField()),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruta_detalle_ruta', to='api.ruta')),
            ],
        ),
    ]
