# Generated by Django 5.0.6 on 2024-07-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutadetalle',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
    ]
