# Generated by Django 5.0.6 on 2024-07-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rutadetalle_entregado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surtidor', models.IntegerField()),
                ('gasolina', models.IntegerField()),
            ],
        ),
    ]
