# Generated by Django 5.0.6 on 2024-07-12 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_solicitud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='gasolina',
            new_name='combustible',
        ),
    ]
